# Generated by Django 4.2.3 on 2023-07-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fotos', models.TextField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Anotações',
            },
        ),
        migrations.CreateModel(
            name='devendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anotacoes.anotacao')),
            ],
            options={
                'verbose_name_plural': 'Devedores',
            },
        ),
    ]
